name: Meteor Publish Reactive (Test Core)

on:
  push:
    branches:
      - alpha
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-test-core
      cancel-in-progress: true
    timeout-minutes: 60

    env:
      PUPPETEER_DOWNLOAD_PATH: /home/runner/.npm/chromium

    name: meteor-core tests

    steps:
      - name: Update and install dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 g++-12

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1

      - name: Cache Node.js modules and Meteor
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.meteor
            meteor-core/.meteor
            meteor-core/.babel-cache
            meteor-core/dev_bundle
            /home/runner/.npm/chromium
          key: ${{ runner.os }}-node-meteor-${{ hashFiles('**/package-lock.json', 'meteor-core/meteor') }}
          restore-keys: |
            ${{ runner.os }}-node-meteor-

      - name: Install dependencies
        run: npm install

      - name: Prepare Meteor core
        run: |
          git submodule update --init --recursive
          ./meteor-core/meteor --get-ready

      - name: Run Core Tests
        run: npm run test:core
